# Generated by Django 6.0.4 on 2026-04-25 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calorie_target', models.FloatField(default=2000)),
                ('daily_protein_target', models.FloatField(default=80)),
                ('max_cheat_calories_per_day', models.FloatField(default=300)),
                ('max_cheat_meals_per_day', models.IntegerField(default=2)),
                ('goal', models.CharField(default='cut', max_length=10)),
                ('points', models.IntegerField(default=0)),
                ('daily_water_goal', models.FloatField(default=3000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
