# Generated by Django 6.0.4 on 2026-04-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
