# Generated by Django 6.0.4 on 2026-04-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_profile_profile_image_profile_start_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_steps_target',
            field=models.IntegerField(default=8000),
        ),
        migrations.AddField(
            model_name='profile',
            name='steps',
            field=models.IntegerField(default=0),
        ),
    ]
