# Generated by Django 6.0.4 on 2026-04-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_profile_daily_steps_target_profile_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='steps',
        ),
        migrations.AlterField(
            model_name='profile',
            name='daily_steps_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(choices=[('fat_loss', 'Fat Loss'), ('muscle_gain', 'Muscle Gain'), ('maintain', 'Maintain')], default='fat_loss', max_length=20),
        ),
    ]
