# Generated by Django 6.0.4 on 2026-05-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_profile_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
