# Generated by Django 6.0.4 on 2026-04-29 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutrition', '0002_alter_meallog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meallog',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
