# Generated by Django 6.0.4 on 2026-04-29 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nutrition', '0004_alter_waterintake_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheatMeal',
        ),
    ]
