# Generated by Django 6.0.4 on 2026-04-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submuscle',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submuscle',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='submuscles/'),
        ),
    ]
