# Generated by Django 6.0.4 on 2026-04-25 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0002_submuscle_description_submuscle_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsession',
            name='muscle_group',
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='sub_muscle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='Workouts.submuscle'),
            preserve_default=False,
        ),
    ]
