# Generated by Django 6.0.4 on 2026-04-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0003_remove_workoutsession_muscle_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musclegroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='muscles/'),
        ),
    ]
