# Generated by Django 6.0.4 on 2026-04-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0004_musclegroup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='submuscle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='submuscles/'),
        ),
    ]
