# Generated by Django 6.0.4 on 2026-05-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0005_submuscle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exercise',
            name='steps',
            field=models.TextField(blank=True, help_text='Write each step on a new line'),
        ),
    ]
